import React from 'react';
import { BookOpen, ChevronLeft } from 'lucide-react';

const TermsOfService = () => {
    return (
        <div className="min-h-screen flex flex-col premium-gradient bg-slate-950 text-slate-50 selection:bg-blue-500/30">
            <div className="relative z-10 flex-grow max-w-4xl mx-auto px-6 py-16 w-full">
                <nav className="flex flex-col md:flex-row justify-between items-center gap-6 mb-12">
                    <button
                        onClick={() => window.location.href = '/'}
                        className="flex items-center gap-2 text-slate-400 hover:text-white transition-colors"
                    >
                        <ChevronLeft className="w-5 h-5" /> Back to Home
                    </button>
                    <div className="flex flex-wrap items-center justify-center gap-4 text-sm font-medium text-slate-400">
                        <a href="/" className="hover:text-blue-400 transition-colors">Home</a>
                        <a href="?page=privacy" className="hover:text-blue-400 transition-colors">Privacy Policy</a>
                        <a href="?page=terms" className="hover:text-blue-400 transition-colors">Terms of Service</a>
                        <a href="mailto:student18171@gmail.com" className="hover:text-blue-400 transition-colors">Contact Us</a>
                        <a href="https://shivam-portfolio-gamma-ruby.vercel.app/" target="_blank" rel="noreferrer" className="hover:text-blue-400 transition-colors">About Us</a>
                    </div>
                </nav>

                <div className="glass-card p-10 md:p-14 rounded-[2.5rem]">
                    <div className="flex items-center gap-4 mb-10">
                        <div className="p-3 bg-indigo-500/10 rounded-2xl">
                            <BookOpen className="w-8 h-8 text-indigo-400" />
                        </div>
                        <h1 className="text-4xl font-black text-white">Terms of Service</h1>
                    </div>

                    <div className="space-y-8 text-slate-300 leading-relaxed">
                        <p>Last updated: {new Date().toLocaleDateString()}</p>

                        <section className="space-y-4">
                            <h2 className="text-2xl justify-start font-bold text-white">1. Agreement to Terms</h2>
                            <p>By viewing or using Resume.AI, you agree to be bound by these Terms of Service. If you disagree with any part of the terms, you must discontinue your use of our service immediately.</p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl justify-start font-bold text-white">2. Intellectual Property Rights</h2>
                            <p>Unless otherwise indicated, the Site and Services are our proprietary property. All source code, databases, functionality, software, website designs, audio, video, text, photographs, and graphics on the Site are owned or controlled by us, and are protected by copyright and trademark laws.</p>
                            <p>You may use the resume analysis reports generated by the Site for your personal, non-commercial use only.</p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl justify-start font-bold text-white">3. User Representations</h2>
                            <p>By using the Site, you represent and warrant that:</p>
                            <ul className="list-disc pl-6 space-y-2 text-slate-400">
                                <li>All registration information you submit will be true, accurate, current, and complete.</li>
                                <li>You have the legal capacity to comply with these Terms of Service.</li>
                                <li>You will not access the Site through automated or non-human means unless explicitly authorized.</li>
                                <li>You will not use the Site for any illegal or unauthorized purpose.</li>
                                <li>The documents uploaded for analysis do not contain confidential corporate data, classified information, or sensitive personal material from third parties without authorization.</li>
                            </ul>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl justify-start font-bold text-white">4. Advertising and Third-Party Links</h2>
                            <p>We use Google AdSense and other advertising partners. We allow advertisers to display advertisements and other information in certain areas of the Site. If you interact with these advertisements, your activity is subject to the terms and privacy conditions of the third-party ad networks.</p>
                            <p>The Site may contain links to third-party websites. We do not endorse, monitor, or have any control over these external sites and are not responsible for their content or data collection practices.</p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl justify-start font-bold text-white">5. Disclaimer and Limitation of Liability</h2>
                            <p>The Site acts as a guidance tool and resume optimization utility. We do not guarantee that using Resume.AI will result in job offers, interviews, or career advancement. The Site is provided on an "AS-IS" and "AS-AVAILABLE" basis.</p>
                            <p>In no event will we be liable to you or any third party for any direct, indirect, consequential, exemplary, incidental, special, or punitive damages arising from your use of the site.</p>
                        </section>

                        <section className="space-y-4">
                            <h2 className="text-2xl justify-start font-bold text-white">6. Contact Information</h2>
                            <p>For questions or concerns regarding these Terms of Service, please contact us at: <a href="mailto:student18171@gmail.com" className="text-indigo-400 hover:text-indigo-300">student18171@gmail.com</a></p>
                        </section>
                    </div>
                </div>
            </div>
        </div>
    );
};

export default TermsOfService;
